webroot/mail/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^write/?$', 'mail.views.write', name='write'),
    url(r'^attachment/(?P<hash>[a-z0-9]+)/?$', 'mail.views.attachment', name='attachment'),
    url(r'^check/(?P<user>[a-z0-9]+)/(?P<mail>[a-z0-9]+)/?$', 'mail.views.check', name='check'),
)

webroot/member/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # member/profile/ 관련 url
    url(r'^profile/$', 'member.views.profile', name='profile'),
    url(r'^profile/(\d+)/$', 'member.views.profile', name='profile'),
    url(r'^profile/add_award/$', 'member.views.add_award', name='add_award'),
    url(r'^profile/delete_award/(\d+)/$', 'member.views.delete_award', name='delete_award'),
    url(r'^profile/delete_career/(\d+)/$', 'member.views.delete_career', name='delete_career'),
    url(r'^profile/add_career/$', 'member.views.add_career', name='add_career'),
)

webroot/somain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # default admin
    url(r'^django_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^django_admin/', include(admin.site.urls)),

    # structure
    url(r'^$', 'structure.views.main'),
    # url(r'^edit_profile/$', 'structure.views.edit_profile', name='edit_profile'),
    url(r'^check_id/$', 'member.views.check_id', name='check_id'),

    # django-registration
    url(r'^accounts/', include('registration.backends.default.urls')),

    # manager
    url(r'^admin/', include('manager.urls', namespace='manager')),

    # member
    url(r'^member/', include('member.urls', namespace='member')),
    
    # korzip / lecture / mail
    url(r'^korzip/', include('korzip.urls', namespace='korzip')),
    url(r'^lecture/', include('lectureroom.urls', namespace='lecture')),
    url(r'^mail/', include('mail.urls', namespace='mail')),

    # Test
    url(r'^send_mail_test/', 'structure.mail.send_staff_view', name='send_staff'),

    # document
    url(r'^document/', include('document.urls', namespace='document')),

    # Notice
    url(r'^notice/', include('structure.urls_notice', namespace='notice')),

    # Mobile API
    url(r'^mobile/', include('mobile.urls', namespace='mobile')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

webroot/member/models.py
#-*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.db import models
#from django.utils.translation import ugettext_lazy as _



TYPE_GENDER_CHOICES = (
    ('M', '남자'),
    ('F', '여자'),
)

class Type(models.Model):
    priority = models.IntegerField(blank=True)
    visibility = models.BooleanField(default=True)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

class EducationLevel(models.Model):
    priority = models.IntegerField(blank=True)
    visibility = models.BooleanField(default=True)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

class Military(models.Model):
    priority = models.IntegerField(blank=True)
    visibility = models.BooleanField(default=True)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

# 기수
class CourseTerm(models.Model):
    priority = models.IntegerField(blank=True)
    visibility = models.BooleanField(default=True)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

# 진행 수료 탈락...등
class CourseStatus(models.Model):
    priority = models.IntegerField(blank=True)
    visibility = models.BooleanField(default=True)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

# 단계
class CourseStep(models.Model):
    priority = models.IntegerField(blank=True)
    visibility = models.BooleanField(default=True)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title


import datetime

class SomaUserManager(BaseUserManager):
    def create_user(
        self,
        username,
        first_name,
        last_name,
        email,
        age,
        gender,
        birthday,
        rr_number,
        home_number,
        phone_number,
        education_level,
        military,
        photo,
        school,
        course_term,
        course_status,
        course_step,
        zipcode,
        address1,
        address2,
        google,
        twitter,
        facebook,
        type,
        password=None
    ):
        user = self.model(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            type=type,
            age=age,
            gender=gender,
            birthday=birthday,
            rr_number=rr_number,
            home_number=home_number,
            phone_number=phone_number,
            education_level=education_level,
            military=military,
            photo=photo,
            school=school,
            course_term=course_term,
            course_status=course_status,
            course_step=course_step,
            zipcode=zipcode,
            address1=address1,
            address2=address2,
            google=google,
            twitter=twitter,
            facebook=facebook,
        )

        # log = create_log(
        #     username,
        #     '1',
        #     username + ', ' + first_name + last_name + u' 회원가입',
        #     datetime.datetime.now()
        # )
        # print log
        # log.save()
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
        self,
        username,
        password,
        first_name='Soma',
        last_name='Admin',
        email='somain.kr@gmail.com',
        type=None,
        age=100,
        gender='M',
        birthday=datetime.datetime.now().strftime("%Y-%m-%d"),
        rr_number='111111-1111111',
        home_number='02-6933-0701',
        phone_number='02-6933-0705',
        education_level=None,
        military=None,
        photo='/static/img/logo.gif',
        school='SW Maestro',
        course_term=None,
        course_status=None,
        course_step=None,
        zipcode='135-565',
        address1='서울특별시 강남구 테헤란로',
        address2='311 아남타워빌딩',
        google='SW Maestro',
        twitter='SW Maestro',
        facebook='SW Maestro'
    ):
        # if len(Type.objects.all()) == 0:
        #     from member.management.commands import createinitialdata
        #     createinitialdata.create_type()

        user = self.create_user(
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
            email=email,
            # type=Type.objects.get(title=u'시스템 관리자'),
            type=None,
            age=age,
            gender=gender,
            birthday=birthday,
            rr_number=rr_number,
            home_number=home_number,
            phone_number=phone_number,
            education_level=None,
            military=None,
            photo=photo,
            school=school,
            course_term=None,
            course_status=None,
            course_step=None,
            zipcode=zipcode,
            address1=address1,
            address2=address2,
            google=google,
            twitter=twitter,
            facebook=facebook,
        )
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.is_approval = True
        user.is_receive_mail = True
        user.is_receive_staff_mail = True

        user.save(using=self._db)
        return user


class SomaUser(AbstractUser):
    # 이미 있는 것
    # username, first_name, last_name, email,
    # password, groups, user_permissions,
    # is_staff, is_active, is_superuser,
    # last_login, date_joined

    type = models.ForeignKey(Type, blank=True, null=True);
    age = models.IntegerField("나이")
    gender = models.CharField("성별", max_length=1, choices=TYPE_GENDER_CHOICES)
    birthday = models.DateField("생일")
    rr_number = models.CharField("주민등록번호", max_length=14)
    home_number = models.CharField("자택전화", max_length=14)
    phone_number = models.CharField("휴대전화", max_length=14)
    education_level = models.ForeignKey(EducationLevel, blank=True, null=True)
    military = models.ForeignKey(Military, blank=True, null=True)
    photo = models.ImageField("사진", upload_to='photo/')
    course_term = models.ForeignKey(CourseTerm, blank=True, null=True)
    course_status = models.ForeignKey(CourseStatus, blank=True, null=True)
    course_description = models.TextField("상태 사유", blank=True) # status에 대한 이유(탈퇴.등)
    course_step = models.ForeignKey(CourseStep, blank=True, null=True)

    # 우편번호
    zipcode = models.CharField("우편번호", max_length=10)
    address1 = models.CharField("주소1", max_length=100)
    address2 = models.CharField("주소2", max_length=50)

    # 선택사항
    google = models.CharField("구글 계정", max_length=100, blank=True)
    school = models.CharField("학교", max_length=100, blank=True)
    twitter = models.CharField("트위터 계정", max_length=100, blank=True)
    facebook = models.CharField("페이스북 계정", max_length=100, blank=True)

    # Push
    android_registration_id = models.CharField("GCM Registration ID", max_length=400, blank=True)

    # 권한
    '''
    기본적으로 제공되는 권한
    is_active
        자동가입을 막기 위한 메일 인증상태(django-registration)

    is_staff
        스태프 권한. 사무국 직원분들의 권한

    is_superuser
        관리자 권한. 개발자들의 권한

    추가로 정의한 권한
    is_approval
        멘티, 멘토 권한. 사무국에 의해 활동이 승인된 계정상태

    is_receive_mail
        멘티, 멘토의 경우 공지메일을 받을 지

    is_receive_staff_mail
        관리자의 경우 메일을 받을 지



    이 외에는 SomaUser의 type을 사용한다
    '''
    is_approval = models.BooleanField(default=False)
    is_receive_mail = models.BooleanField(default=True)
    is_receive_staff_mail = models.BooleanField(default=False)

    objects = SomaUserManager()

    USERNAME_FIELD = 'username'

    def __unicode__(self):
        return u'%s%s' % (self.last_name, self.first_name)

    def json(self):
        from mobile.api import convert_strftime_day

        if self is None:
            return u'None'

        return {
            'username': self.username,
            'name': self.last_name + self.first_name,
            'type': self.type.title,
            'age': self.age,
            'gender': self.gender,
            'birthday': convert_strftime_day(self.birthday),
            'photo': self.photo.url,
            'course_term': self.course_term.title,
            'course_status': self.course_status.title,
            'course_description': self.course_description,
            'course_step': self.course_step.title
        }

# 경력사항
class Career(models.Model):
    member = models.ForeignKey(SomaUser)
    title = models.CharField('근무처', max_length=100)
    start_date = models.DateField('시작날짜')
    end_date = models.DateField('종료날짜')
    description = models.TextField()

    def __unicode__(self):
        return self.title

# 수상내역
class Award(models.Model):
    member = models.ForeignKey(SomaUser)
    title = models.CharField('수상기관', max_length=100)
    date = models.DateField()
    description = models.TextField()

    def __unicode__(self):
        return self.title

webroot/member/views.py
#-*- coding: utf-8 -*-
import hashlib
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from forms import AwardForm, CareerForm
from models import SomaUser
from models import Award, Career

# 멘티들의 정보에 접근할 수 있는 관리자 권한이 있는지 리턴
# 현재는 is_staff와 is_superuser만 접근가능
def is_admin(user):
    if user.is_staff == False and user.is_superuser == False:
        return False
    else:
        return True

@login_required
def profile(request, id=None):
    if id == None:
        user = request.user
    else:
        if is_admin(request.user):
            user = SomaUser.objects.get(id=id)
        else:
            return redirect('manager:only_admin')

    awards = Award.objects.filter(member=user).order_by('-date')
    careers = Career.objects.filter(member=user).order_by('-end_date')
    d = {
        'user': user,
        'awards': awards,
        'careers': careers,
    }

    return render_to_response('member/profile.html', d)

def edit_profile(request, id=None):
    if id == None:
        user = request.user
    else:
        user = SomaUser.objects.get(id=id)

def add_award(request):
    if request.method == 'POST':
        form = AwardForm(request.POST)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data['title']
            date = form.cleaned_data['date']
            description = form.cleaned_data['description']

            award = Award(member=user, title=title, date=date, description=description)
            award.save()

            return redirect('member:profile')
        else:
            return render_to_response('member/add_award.html', {'form': form,}, RequestContext(request))    
    else:
        form = AwardForm()
        return render_to_response('member/add_award.html', {'form': form,}, RequestContext(request))

def delete_award(request, id):
    Award.objects.get(id=id).delete()
    return redirect('member:profile')

def delete_career(request, id):
    Career.objects.get(id=id).delete()
    return redirect('member:profile')

def add_career(request):
    if request.method == 'POST':
        form = CareerForm(request.POST)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data['title']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            description = form.cleaned_data['description']

            award = Career(member=user, title=title, start_date=start_date, end_date=end_date, description=description)
            award.save()

            # return HttpResponse(u'경력사항(' + title + u') 이 등록되었습니다')
            # redirect를 view로 하려면 어떻게 쓰는것이 맞는지?
            return redirect('member:profile')
        else:
            return render_to_response('member/add_career.html', {'form': form,}, RequestContext(request))    
    else:
        form = CareerForm()
        return render_to_response('member/add_career.html', {'form': form,}, RequestContext(request))


def check_id(request):
    print request
    print request.GET

    return HttpResponse(False)

webroot/templates/member/add_award.html
{% extends 'registration/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}

{% block content %}


<div class="content container-fluid">
	<div class="row-fluid">
		<div class="span8 offset2">
			<h2 class="page-title">수상내역 추가  <small>Award Career</small></h2>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span8 offset2">
			<section class="widget">
				<header>
					<legend class="section"><i class="icon-file"></i> 유의사항  <small>Terms &amp; conditions of use</small></legend>
				</header>
				<div class="body">
					<form class="form-horizontal label-left" novalidate="novalidate" method="POST" data-validate="parsley">
						{% csrf_token %}
						<div class="row-fluid">
							<div class="span12" style="padding: 10px;   ">
								제 1 조 (목적)<br/>
								<br/>
								이 약관은 네이버 주식회사 ("회사" 또는 "네이버")가 제공하는 네이버, 미투데이(me2day.net) 및 네이버와 미투데이 관련 제반 서비스의 이용과 관련하여 회사와 회원과의 권리, 의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.<br/>
								제 2 조 (정의)<br/>
								<br/>
								이 약관에서 사용하는 용어의 정의는 다음과 같습니다.<br/>
								①"서비스"라 함은 구현되는 단말기(PC, TV, 휴대형단말기 등의 각종 유무선 장치를 포함)와 상관없이 "회원"이 이용할 수 있는 네이버, 미투데이(me2day.net) 및 네이버와 미투데이 관련 제반 서비스를 의미합니다.<br/>
								②"회원"이라 함은 회사의 "서비스"에 접속하여 이 약관에 따라 "회사"와 이용계약을 체결하고 "회사"가 제공하는 "서비스"를 이용하는 고객을 말합니다.
								③"아이디(ID)"라 함은 "회원"의 식별과 "서비스" 이용을 위하여 "회원"이 정하고 "회사"가 승인하는 문자와 숫자의 조합을 의미합니다.<br/>
								④"비밀번호"라 함은 "회원"이 부여 받은 "아이디와 일치되는 "회원"임을 확인하고 비밀보호를 위해 "회원" 자신이 정한 문자 또는 숫자의 조합을 의미합니다.<br/>
								⑤"유료서비스"라 함은 "회사"가 유료로 제공하는 각종 온라인디지털콘텐츠(각종 정보콘텐츠, VOD, 아이템 기타 유료콘텐츠를 포함) 및 제반 서비스를 의미합니다.
								⑥"포인트"라 함은 서비스의 효율적 이용을 위해 회사가 임의로 책정 또는 지급, 조정할 수 있는 재산적 가치가 없는 "서비스" 상의 가상 데이터를 의미합니다.<br/>
								⑦"게시물"이라 함은 "회원"이 "서비스"를 이용함에 있어 "서비스상"에 게시한 부호ㆍ문자ㆍ음성ㆍ음향ㆍ화상ㆍ동영상 등의 정보 형태의 글, 사진, 동영상 및 각종 파일과 링크 등을 의미합니다.<br/>
							</div>
						</div>
						<fieldset>
							
						</fieldset>
						<fieldset>
							<legend class="section"><i class="icon-circle-blank"></i>    수상 정보</legend>
							<div class="control-group">
								<label for="{{ form.title.id_for_label }}" class="control-label">
									{{ form.title.label }}
								</label>
								<div class="controls controls-row">
									{{ form.title }}
									<span class="help-inline">
										{{ form.title.errors }}
									</span>
								</div>
							</div>

							<div class="control-group">
								<label for="{{ form.date.id_for_label }}" class="control-label">
									{{ form.date.label }}
								</label>
								<div class="controls controls-row">
									{{ form.date }}
									<span class="help-inline">
										{{ form.date.errors }}
									</span>
								</div>
							</div>

							<div class="control-group">
								<label for="{{ form.description.id_for_label }}" class="control-label">
									{{ form.description.label }}
								</label>
								<div class="controls controls-row">
									{{ form.description }}
									<span class="help-inline">
										{{ form.description.errors }}
									</span>
								</div>
							</div>

						</fieldset>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary span9">수상내역 추가</button>
						</div>
					</form>
				</div>
			</section>
		</div>
	</div>
</div>
</div>
{% endblock %}


{% block bottom_script %}
<!-- jquery and friends -->
<script src="{% static 'lib/jquery/jquery.1.9.0.min.js' %}"> </script>
<script src="{% static 'lib/jquery/jquery-migrate-1.1.0.min.js' %}"> </script>

<!-- jquery plugins -->
<script src="{% static 'js/jquery/jquery.maskedinput.js' %}"></script>
<script src="{% static 'js/parsley/parsley.js' %}"> </script>
<script src="{% static 'js/jquery/jquery.uniform.js' %}"></script>
<script src="{% static 'js/jquery/jquery.select2.js' %}"></script>
<script src="{% static 'js/jquery/jquery.autogrow-textarea.js' %}"></script>


<!--backbone and friends -->
<script src="{% static 'js/backbone/underscore-min.js' %}"></script>

<!-- bootstrap default plugins -->
<script src="{% static 'js/bootstrap/bootstrap-transition.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-collapse.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-alert.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-tooltip.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-popover.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-button.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-dropdown.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-modal.js' %}"></script>

<!-- bootstrap custom plugins -->
<script src="{% static 'js/bootstrap/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-select.js' %}"></script>


<script src="{% static 'js/bootstrap/bootstrap-switch.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-colorpicker.js' %}"></script>

<!-- basic application js-->
<script src="{% static 'js/bootstrap/app.js' %}"></script>
<script src="{% static 'js/bootstrap/settings.js' %}"></script>

<!-- page specific -->
<script src="{% static 'js/forms-elemets.js' %}"></script>
{% endblock %}

{% block after_script %}
{% endblock %}

webroot/templates/member/auth.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<link href="{% static 'css/member/auth.css' %}" rel="stylesheet" media="screen">
<form class="form-member" action="{% url 'member:auth' %}" method="post">{% csrf_token %}
	<legend>회원가입 - 이메일 인증</legend>
	{{ form.email }}
	{{ form.email.errors }}
		<div class="checkbox">
		{{ form.terms_agree.label_tag }}{{ form.terms_agree }}{{ form.terms_agree.errors }}
		</div>
	<input type="submit" value="인증 메일 보내기" class="btn btn-large btn-primary btn-block">
</form>
{% endblock %}

webroot/templates/member/confirm.html
{% include "header.html" %}
<div class="jumbotron">
	<h1>{{ head }}</h1>
	<p>{{ message }}</p>
</div>
{% include "footer.html" %}

webroot/templates/member/profile.html
{% extends 'registration/base.html' %}
{% load staticfiles %}

{% block title %}Profile{% endblock %}

{% block style %}
<style>
</style>
{% endblock %}

{% block content %}
<div class="content container-fluid">
	<div class="row-fluid">
		<div class="span8 offset2">
			<h2 class="page-title">프로필  <small>Profile</small></h2>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span8 offset2">
			<section class="widget">
				<fieldset>

					<legend class="section"><i class="icon-circle-blank"></i>  신상 정보 &nbsp;&nbsp;&nbsp;<a href="#">Edit</a></legend>
					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							아이디
						</div>
						<div class="span9 offset1">
							{{ user.username }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							이름
						</div>
						<div class="span9 offset1">
							{{ user.first_name }} {{ user.last_name }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							이메일
						</div>
						<div class="span9 offset1">
							{{ user.email }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							나이
						</div>
						<div class="span9 offset1">
							{{ user.age }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							성별
						</div>
						<div class="span9 offset1">
							{{ user.get_gender_display }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							생일
						</div>
						<div class="span9 offset1">
							{{ user.birthday }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							나이
						</div>
						<div class="span9 offset1">
							{{ user.age }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							집 전화번호
						</div>
						<div class="span9 offset1">
							{{ user.home_number }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							휴대전화 번호
						</div>
						<div class="span9 offset1">
							{{ user.phone_number }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							학력
						</div>
						<div class="span9 offset1">
							{{ user.get_education_level_display }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							병역사항
						</div>
						<div class="span9 offset1">
							{{ user.get_military_display }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							학교명
						</div>
						<div class="span9 offset1">
							{{ user.school }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							구글 계정
						</div>
						<div class="span9 offset1">
							{{ user.google }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							트위터 계정
						</div>
						<div class="span9 offset1">
							{{ user.twitter }}
						</div>
					</div>

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							페이스북 계정
						</div>
						<div class="span9 offset1">
							{{ user.facebook }}
						</div>
					</div>

				</fieldset>

				<fieldset>
					<legend class="section"><i class="icon-circle-blank"></i> 수상 정보 &nbsp;&nbsp;&nbsp;<a href="{% url 'member:add_award' %}">Add</a></legend>
					{% for award in awards %}

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							{{ award.date }}
						</div>
						<div class="span9 offset1">
							{{ award.title }}
						</div>
					</div>
					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							<form action="/member/profile/" method="POST">
								<a href="{% url 'member:delete_award' award.id %}">Delete</a>
							</form>
						</div>
						<div class="span9 offset1" style="margin-bottom: 50px; word-break: break-all">
							{{ award.description }}
						</div>
					</div>
					{% endfor %}
				</fieldset>

				<fieldset>
					<legend class="section"><i class="icon-circle-blank"></i> 경력사항 &nbsp;&nbsp;&nbsp;<a href="{% url 'member:add_career' %}">Add</a></legend>
					{% for career in careers %}

					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							{{ career.start_date }}<br/>
							~ {{ career.end_date }}
						</div>
						<div class="span9 offset1">
							{{ career.title }}
						</div>
					</div>
					<div class="row-fluid">
						<div class="span2" style="text-align: right;">
							<form action="/member/profile/" method="POST">
								<a href="{% url 'member:delete_career' career.id %}">Delete</a>
							</form>
						</div>
						<div class="span9 offset1" style="margin-bottom: 50px; word-break: break-all">
							{{ career.description }}
						</div>
					</div>
					{% endfor %}
				</fieldset>


			</section>
		</div>
	</div>
</div>
</div>
{% endblock %}


{% block bottom_script %}
<!-- jquery and friends -->
<script src="{% static 'lib/jquery/jquery.1.9.0.min.js' %}"> </script>
<script src="{% static 'lib/jquery/jquery-migrate-1.1.0.min.js' %}"> </script>

<!-- jquery plugins -->
<script src="{% static 'js/jquery/jquery.maskedinput.js' %}"></script>
<script src="{% static 'js/parsley/parsley.js' %}"> </script>
<script src="{% static 'js/jquery/jquery.uniform.js' %}"></script>
<script src="{% static 'js/jquery/jquery.select2.js' %}"></script>
<script src="{% static 'js/jquery/jquery.autogrow-textarea.js' %}"></script>


<!--backbone and friends -->
<script src="{% static 'js/backbone/underscore-min.js' %}"></script>

<!-- bootstrap default plugins -->
<script src="{% static 'js/bootstrap/bootstrap-transition.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-collapse.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-alert.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-tooltip.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-popover.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-button.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-dropdown.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-modal.js' %}"></script>

<!-- bootstrap custom plugins -->
<script src="{% static 'js/bootstrap/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-select.js' %}"></script>


<script src="{% static 'js/bootstrap/bootstrap-switch.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-colorpicker.js' %}"></script>

<!-- basic application js-->
<script src="{% static 'js/bootstrap/app.js' %}"></script>
<script src="{% static 'js/bootstrap/settings.js' %}"></script>

<!-- page specific -->
<script src="{% static 'js/forms-elemets.js' %}"></script>
{% endblock %}

{% block after_script %}
{% endblock %}