webroot/lectureroom/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^/?$', 'lectureroom.views.main', name='main'),
    url(r'^my/?$', 'lectureroom.views.mylist', name='mylist'),
    url(r'^list/?$', 'lectureroom.views.list', name=''),
    url(r'^new/?$', 'lectureroom.views.new', name='new'),
    url(r'^new/check/?$', 'lectureroom.views.check', name='check'),
    url(r'^new/recent/?$', 'lectureroom.views.recent', name='recent'),
    url(r'^delete/?$', 'lectureroom.views.delete', name='delete'),
    url(r'^view/(\d+)/?$', 'lectureroom.views.view', name='view'),
)

webroot/mail/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^write/?$', 'mail.views.write', name='write'),
    url(r'^attachment/(?P<hash>[a-z0-9]+)/?$', 'mail.views.attachment', name='attachment'),
    url(r'^check/(?P<user>[a-z0-9]+)/(?P<mail>[a-z0-9]+)/?$', 'mail.views.check', name='check'),
)

webroot/somain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # default admin
    url(r'^django_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^django_admin/', include(admin.site.urls)),

    # structure
    url(r'^$', 'structure.views.main'),
    # url(r'^edit_profile/$', 'structure.views.edit_profile', name='edit_profile'),
    url(r'^check_id/$', 'member.views.check_id', name='check_id'),

    # django-registration
    url(r'^accounts/', include('registration.backends.default.urls')),

    # manager
    url(r'^admin/', include('manager.urls', namespace='manager')),

    # member
    url(r'^member/', include('member.urls', namespace='member')),
    
    # korzip / lecture / mail
    url(r'^korzip/', include('korzip.urls', namespace='korzip')),
    url(r'^lecture/', include('lectureroom.urls', namespace='lecture')),
    url(r'^mail/', include('mail.urls', namespace='mail')),

    # Test
    url(r'^send_mail_test/', 'structure.mail.send_staff_view', name='send_staff'),

    # document
    url(r'^document/', include('document.urls', namespace='document')),

    # Notice
    url(r'^notice/', include('structure.urls_notice', namespace='notice')),

    # Mobile API
    url(r'^mobile/', include('mobile.urls', namespace='mobile')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

webroot/lectureroom/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

TYPE_LECTURE_CHOICES = (
    ('1', '과정멘토링'),
    ('2', '집체교육'),
    ('3', '스터디'),
    ('4', '기타'),
    ('5', '자유멘토링'),
    ('6', '특강'),
)

# TYPE_ROOM_CHOICES = (
#     ('1', '아남타워 [기타]'),
#     ('2', '연수센터 7층 [해찬1]'),
#     ('3', '연수센터 7층 [해찬2]'),
#     ('4', '연수센터 7층 [해찬3]'),
#     ('5', '연수센터 2층 [아람2-1]'),
#     ('6', '연수센터 2층 [아람2-2]'),
#     ('7', '연수센터 2층 [아람2-3]'),
#     ('8', '연수센터 7층 [아람7-6]'),
#     ('9', '연수센터 7층 [아람7-5_3기 3단계]'),
#     ('10', '연수센터 7층 [아람7-4_3기 3단계]'),
#     ('11', '연수센터 7층 [아람7-7]'),
#     ('12', '연수센터 2층 [커뮤니티]'),
#     ('13', '연수센터 7층 [아람7-3_3기 3단계]'),
#     ('14', '연수센터 7층 [아람7-2_3기 3단계]'),
#     ('15', '연수센터 7층 [아람7-1_3기 3단계]'),
# )
class LectureRoom(models.Model):
    name = models.CharField('강의실 이름', max_length=50)

    def get_name(self):
        return self.name

class LectureBlockManager(models.Manager):
    def new_block(self, name, content, start_date, end_date, room):
        block = self.model(
                name=name,
                content=content,
                start_date=start_date,
                end_date=end_date,
                room=room,
            )
        block.save()
        return block

class LectureBlock(models.Model):
    name = models.CharField('차단 제목', max_length=100)
    content = models.TextField('차단 사유')
    start_date = models.DateTimeField('시작일시', blank=True, db_index=True)
    end_date = models.DateTimeField('종료일시', blank=True, db_index=True)
    room = models.ForeignKey(LectureRoom)

    objects = LectureBlockManager()

class LectureManager(models.Manager):
    def new_lecture(self, user, team, name, room, count, xtype, start, end, admin, admin_tel, message):
        result = {
            'success': False,
            'data': '',
        }

        # 강의실이 차단된(Blocked) 강의실인지 먼저 확인한다.
        '''
            지정된 강의실이:
                1. start 가 start_date 와 end_date 사이에 있을 경우
                2. end 가 start_date 와 end_date 사이에 있을 경우
        '''
        check = self.check_lecture(room, start, end)
        if type(check) != bool:
            return result
        else:
            lecture = self.model(
                user=user,
                team=team,
                name=name,
                room=room,
                count=count,
                type=xtype,
                start=start,
                end=end,
                admin=admin,
                admin_tel=admin_tel,
                message=message,
            )
            lecture.save()
            if lecture:
                result['success'] = True
                result['data'] = lecture
            return result

    def check_lecture(self, room, start, end):
        block = LectureBlock.objects.filter(Q(Q(start_date__range=(start, end)) | Q(end_date__range=(start, end)) | Q(start_date__lte=start, end_date__gte=end)), room=room)
        exist = super(LectureManager, self).filter(Q(Q(start__range=(start, end)) | Q(end__range=(start, end)) | Q(start__lte=start, end__gte=end)), room=room)
        print block

        if block.count() > 0:
            return block
        elif exist.count() > 0:
            return exist
        else:
            return True

    def remove_lecture(self):

        return False

    def get_lecture(self, start, end):
        result = {
            'count': 0,
            'data': [],
        }

        lectures = super(LectureManager, self).filter(start__gte=start, end__lte=end)
        for lecture in lectures:
            result['count'] += 1
            result['data'].append(lecture)

        return result

class Lecture(models.Model):
    user = models.ForeignKey(User)
    team = models.CharField('소속', max_length=30)
    name = models.CharField('회의명', max_length=30)
    room = models.ForeignKey(LectureRoom)
    count = models.IntegerField('참석 인원')
    type = models.CharField('사용 목적', max_length=1, choices=TYPE_LECTURE_CHOICES)
    start = models.DateTimeField('시작일시', db_index=True)
    end = models.DateTimeField('종료일시', db_index=True)
    admin = models.CharField('담당자명', max_length=10)
    admin_tel = models.CharField('담당자 연락처', max_length=12)
    message = models.TextField('비고')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = LectureManager()

webroot/lectureroom/forms.py
#-*- coding: utf-8 -*-
from django import forms
from member.widgets import SplitInputWidget
from lectureroom.models import *

TYPE_LECTURE_CHOICES = (
    ('', '-- 선택 --'),
    ('1', '과정멘토링'),
    ('2', '집체교육'),
    ('3', '스터디'),
    ('4', '기타'),
    ('5', '자유멘토링'),
    ('6', '특강'),
)

class LectureForm(forms.Form):
    room = forms.ChoiceField(label='강의실 선택', choices=[], required=True)
    name = forms.CharField(label='회의명', max_length=30, widget=forms.TextInput(attrs={ 'placeholder': '멘토링' }), required=True)
    team = forms.CharField(label='소속', max_length=30, widget=forms.TextInput(attrs={ 'placeholder': '소프트웨어 마에스트로' }), required=False)
    count = forms.IntegerField(label='참석 인원', widget=forms.TextInput(attrs={ 'placeholder': '숫자만 입력하세요' }), required=True)
    type = forms.ChoiceField(label='사용 목적', choices=TYPE_LECTURE_CHOICES, widget=forms.Select, required=True)
    admin = forms.CharField(label='담당자명', widget=forms.TextInput(attrs={ 'placeholder': '홍길동' }), max_length=10)
    admin_tel = forms.CharField(label='담당자 연락처', widget=SplitInputWidget(number=3, each_attrs=[{ 'maxlength': 3 },{ 'maxlength': 4 },{ 'maxlength': 4 }], attrs={ 'style': 'width: 60px' }), required=True)
    message = forms.CharField(label='비고', widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(LectureForm, self).__init__(*args, **kwargs)
        room_choices = [('', '-- 선택 --')]
        for room in LectureRoom.objects.all():
            room_choices.append((room.id, room.name))
        self.fields['room'].choices = room_choices

webroot/lectureroom/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse, Http404
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from .models import Lecture, LectureRoom, LectureBlock
from .forms import LectureForm

from django.contrib.auth.decorators import login_required as login

from time import mktime
from datetime import datetime
import re
import json

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

# 강의실 예약 페이지 메인
@login
def main(request):

    return render_to_response('lectureroom/main.html', {})

# 최근 저장내용 가져오기
@login
def recent(request):
    data = {
        'success': False,
        'result': {}
    }

    lecture = Lecture.objects.filter(user=request.user).order_by('-created_at')[0]
    if not lecture:
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        data['success'] = True
        data['result'] = {
            'name': lecture.name,
            'team': lecture.team,
            'count': lecture.count,
            'type': lecture.type,
            'admin': lecture.admin,
            'admin_tel': lecture.admin_tel,
        }
        return HttpResponse(json.dumps(data), content_type='application/json')

# 강의실 예약 페이지
# 팝업으로 띄우기
@login
def new(request):
    if request.method == 'POST':
        form = LectureForm(request.POST)
        start = request.POST.get('start_date', '')
        end = request.POST.get('end_date', '')

        try:
            # datetime 객체로 변환
            start = datetime.strptime(start, '%Y-%m-%d %p%I:%M')
            end = datetime.strptime(end, '%Y-%m-%d %p%I:%M')
        except Exception, e:
            print start, end
            return HttpResponse('<script> alert("올바른 시간형식이 아닙니다."); history.go(-1) </script>')

        if form.is_valid():
            # print type(form.cleaned_data['message'])
            # return HttpResponse('')
            user_object = request.user
            room_object = LectureRoom.objects.get(id=int(form.cleaned_data['room']))
            # print room_object
            result = Lecture.objects.new_lecture(
                user_object,
                form.cleaned_data['team'],
                form.cleaned_data['name'],
                room_object,
                int(form.cleaned_data['count']),
                form.cleaned_data['type'],
                start,
                end,
                form.cleaned_data['admin'],
                form.cleaned_data['admin_tel'].replace('-', ''),
                form.cleaned_data['message']
            )

            if result['success'] == True:
                return HttpResponse('<script> alert("강의실 예약이 완료되었습니다."); parent.location.reload(); window.close(); </script>')
        else:
            msg = ''
            for error in form.errors:
                if error == 'room':
                    msg = '강의실을 선택하세요.'
                elif error == 'name':
                    msg = '회의명을 입력해주세요.'
                elif error == 'team':
                    msg = '소속을 입력해주세요.'
                elif error == 'count':
                    msg = '참석 인원을 숫자로 입력해주세요.'
                elif error == 'admin':
                    msg = '담당자 이름을 입력해주세요.'
                elif error == 'admin_tel':
                    msg = '담당자 연락처를 입력해주세요.'
            return HttpResponse('<script> alert("' + msg + '"); history.go(-1) </script>')

    d = {}
    d['form'] = LectureForm()

    return render_to_response('lectureroom/new.html', d, RequestContext(request))

# 사용 가능한 강의실인지 확인
@login
def check(request):
    data = {
        'success': False,
        'available': False,
        'why': '',
    }

    room = request.POST.get('room', '')
    start = request.POST.get('start', '')
    end = request.POST.get('end', '')

    if not room:
        data['success'] = False
        data['why'] = '존재하지 않는 강의실입니다.'
        return HttpResponse(json.dumps(data), content_type='application/json')

    try:
        start = datetime.strptime(start, '%Y-%m-%d %p%I:%M')
        end = datetime.strptime(end, '%Y-%m-%d %p%I:%M')
    except Exception, e:
        data['success'] = False
        data['why'] = '올바른 시간 형식이 아닙니다.'
        return HttpResponse(json.dumps(data), content_type='application/json')

    if start == end:
        data['success'] = False
        data['why'] = '시작 날짜와 끝 날짜는 같을 수 없습니다.'
        return HttpResponse(json.dumps(data), content_type='application/json')

    room_object = LectureRoom.objects.get(id=int(room))

    if not room_object:
        data['success'] = False
        data['why'] = '존재하지 않는 강의실입니다.'
        return HttpResponse(json.dumps(data), content_type='application/json')

    available = Lecture.objects.check_lecture(room_object, start, end)
    if available == True:
        data['success'] = True
        data['available'] = True
    else:
        data['success'] = True
        data['available'] = False
        if type(available[0]) == LectureBlock:
            data['why'] = u'사용이 금지된 강의실입니다.\n' + available[0].name + '\n-----\n' + available[0].content + '\n-----\n' + str(available[0].start_date) + ' ~ ' + str(available[0].end_date)
        elif type(available[0]) == Lecture:
            data['why'] = u'이미 예약된 강의가 있습니다.'
        else:
            data['available'] = True

    return HttpResponse(json.dumps(data), content_type='application/json')

@login
def mylist(request):
    d = {}
    d['lectures'] = Lecture.objects.filter(start__gte=datetime.now(), user=request.user).order_by('start')

    return render_to_response('lectureroom/mylist.html', d, RequestContext(request))

@login
def delete(request):
    if request.method == 'POST':
        id = request.POST.get('id', '')
        if id == '':
            return

        lecture = Lecture.objects.get(id=id)
        if not lecture:
            return HttpResponse('<script> alert("존재하지 않는 예약입니다."); history.go(-1) </script>', status=500)

        # 본인만 삭제 가능
        if lecture.user != request.user and not request.user.is_staff:
            raise Http404

        lecture.delete()
        return HttpResponse('<script> alert("예약을 취소하였습니다."); window.close() </script>')

# 강의 예약목록 가져오기
@login
def list(request):
    data = {
        'success': 0,
        'result': [],
    }

    fr = request.GET.get('from', '')
    to = request.GET.get('to', '')

    if fr == '' or to == '':
        return HttpResponse(json.dumps(data), content_type='application/json')

    items = Lecture.objects.get_lecture(datetime.fromtimestamp(int(fr) / 1000), datetime.fromtimestamp(int(to) / 1000))
    data['success'] = 1
    if items['count'] == 0:
        return HttpResponse(json.dumps(data), content_type='application/json')

    for item in items['data']:
        data['result'].append({
            'id': item.id,
            'title': item.name,
            'url': '/lecture/view/' + str(item.id),
            'class': '',
            'room_id': item.room.id,
            'room_name': item.room.name,
            'admin': item.admin,
            'start': int(mktime(item.start.timetuple()) * 1000),
            'end': int(mktime(item.end.timetuple()) * 1000),
        })

    return HttpResponse(json.dumps(data), content_type='application/json')

@login
def view(request, id):
    if not Lecture.objects.filter(id=id).exists():
        raise Http404

    lecture = Lecture.objects.get(id=id)
    d = {
        'title': lecture.name,
        'lecture': lecture,
        'user': request.user,
    }

    return render_to_response('lectureroom/view.html', d, RequestContext(request))

webroot/templates/lectureroom/main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
	<link href="{% static 'css/calendar.orign.css' %}" rel="stylesheet">
	<link href="{% static 'css/powertip.css' %}" rel="stylesheet">
{% endblock %}

{% block page_title %}강의실 예약{% endblock %}
{% block page_subtitle %}강의실 예약목록을 확인합니다.{% endblock %}

{% block content %}
	<div class="container">
		<div class="page-header" style="border-bottom: 0">
			<div class="row-fluid">
				<div class="span12">
					<div class="text-right">
						<a href="{% url 'lecture:new' %}" class="btn btn-dark" onclick="window.open(this.href, '_blank', 'width=350, height=550, toolbar=no, location=no, status=no, menubar=no, scrollbars=yes, resizable=no');return false">강의실 예약하기</a>
						<a href="{% url 'lecture:mylist' %}" class="btn btn-dark" onclick="window.open(this.href, '_blank', 'width=350, height=550, toolbar=no, location=no, status=no, menubar=no, scrollbars=yes, resizable=no');return false">내 예약목록</a>
					</div>
				</div>
			</div>

			<div class="pull-right form-inline">
				<button class="btn btn-dark" data-calendar-view="month">월별 보기</button>
			</div>
			<button class="calendar-btn" data-calendar-nav="prev"><i class="icon-angle-left"></i> 이전</button>
			<h3></h3>
			<button class="calendar-btn" data-calendar-nav="next">다음 <i class="icon-angle-right"></i></button>
		</div>

		<div class="row-fluid">
			<div class="span9">
				<div id="calendar"></div>
			</div>
			<div class="span3">
				<div class="event_div">
					<table id="eventlist" class="event_table">
						<thead>
							<tr>
								<th>일시</th>
								<th>시간</th>
								<th>강의실</th>
								<th>예약자명</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</div>
		</div>
		<div id="calendar"></div>
	</div>
</div>
{% endblock %}

{% block bottom %}
<!-- jquery plugins -->
<script src="{% static 'js/moment/moment.js' %}"></script>
<script src="{% static 'js/jquery/jquery.maskedinput.js' %}"></script>
<script src="{% static 'js/parsley/parsley.js' %}"> </script>
<script src="{% static 'js/jquery/jquery.uniform.js' %}"></script>
<script src="{% static 'js/jquery/jquery.select2.js' %}"></script>
<script src="{% static 'js/jquery/jquery.datatable.js' %}"></script>
<script src="{% static 'js/jquery/jquery.powertip.min.js' %}"></script>

<!--backbone and friends -->
<script src="{% static 'js/backbone/underscore-min.js' %}"></script>
<script src="{% static 'js/backbone/backbone-min.js' %}"></script>
<script src="{% static 'js/backbone/backbone-pageable.js' %}"></script>
<script src="{% static 'js/backgrid/backgrid.js' %}"></script>
<script src="{% static 'js/backgrid/backgrid-paginator.js' %}"></script>

<!-- bootstrap default plugins -->
<script src="{% static 'js/bootstrap/bootstrap-transition.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-collapse.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-alert.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-tooltip.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-popover.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-button.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-dropdown.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-modal.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-tab.js' %}"></script>

<!-- basic application js-->
<script src="{% static 'js/bootstrap/app.js' %}"></script>
<script src="{% static 'js/bootstrap/settings.js' %}"></script>

<!-- page-specific js -->
<script src="{% static 'js/admin/tables-dynamic.js' %}"></script>
<!-- <script src="{% static 'js/forms-elemets.js' %}"></script> -->
<script src="{% static 'js/admin/underscore-min.js' %}"></script>
<script src="{% static 'js/calendar/calendar.min.js' %}"></script>
<script src="{% static 'tpl/calendar/language/ko-KR.js' %}"></script>
<script src="{% static 'js/calendar/calendar.app.js' %}"></script>
{% endblock %}

webroot/templates/lectureroom/mylist.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>내 예약목록</title>

	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.css' %}">
	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.icons.css' %}">
	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.custom.css' %}">

	<link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui-dtpicker.css' %}">
	<style>
		div.datepair input[type="text"] {
			width: 150px;
		}
	</style>
</head>
<body data-tuktuk="boxes">
	<section>
		<header class="bck light">
			<h3 class="on-left text thin">내 예약목록</h3>
		</header>
		<article class="padding scroll">
			<!-- <div class="margin-bottom">
				<button type="button" id="recent_btn" style="width: 100%">
					<span class="icon cloud-download"></span> 최근 입력정보 가져오기
				</button>
			</div>
			 -->
			
			<div class="margin-bottom">
				최근 예약순으로 출력됩니다.
			</div>
			<div class="margin-top margin-bottom">
				<ul class="lecture">
					{% for lecture in lectures %}
						<li>
							<div>
								<strong>{{ lecture.name|escape }}</strong> [{{ lecture.room.get_name }}]<br>
								{{ lecture.start|date:'M d일 H:m' }} ~ {{ lecture.end|date:'M d일 H:m' }}

								<div class="right">
									<a href="javascript:void(0)" data-lecture-id="{{ lecture.id }}">
										<span class="icon trash"></span>
									</a>
								<div>
							</div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</article>
	</section>

	<form id="delete" method="post" action="{% url 'lecture:delete' %}" class="hide">
		{% csrf_token %}
		<input type="hidden" name="id" value="">
	</form>

	<script src="{% static 'js/jquery/jquery.js' %}"></script>
	<script src="{% static 'js/tuktuk/tuktuk.js' %}"></script>
	<script src="{% static 'js/jquery-ui/jquery-ui.js' %}"></script>
	<script src="{% static 'js/jquery-ui/jquery-ui-dtpicker.js' %}"></script>
	<script src="{% static 'js/moment/moment.js' %}"></script>
	<script>
		var on_ready = function() {
			var trashes = $('a[data-lecture-id]');
			var delete_form = $('#delete');

			trashes.click(function() {
				if(confirm('예약을 취소하시겠습니까?')) {
					var id = $(this).data('lecture-id');

					delete_form.children('input[name="id"]').val(id);
					delete_form.submit();
				}
			});
		};

		$(document).ready(on_ready);
	</script>
</body>
</html>

webroot/templates/lectureroom/view.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>예약내용 확인 :: {{ title }}</title>

	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.css' %}">
	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/tuktuk/tuktuk.icons.css' %}">

	<link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui-dtpicker.css' %}">
	<style>
		dl { margin: 0 }
		dt {
			float: left;
			margin: 0;
			padding: 2px 0;
			width: 8em;
			color: gray;
			font-weight: normal;
			clear: left;
		}

		dd {
			margin: 0 0 0 8em;
			padding: 2px 8px;
			border-left: 1px solid silver;
		}
	</style>
</head>
<body data-tuktuk="boxes">
	<section>
		<header class="bck light">
			<h3 class="on-left text thin">강의실 예약내용 확인</h3>
		</header>
		<article class="padding">
			<dl>
				<dt>예약명</dt>
				<dd>{{ lecture.name }}</dd>
				<dt>담당자</dt>
				<dd>{{ lecture.admin|escape }}</dd>
				<dt>담당자 연락처</dt>
				<dd>{{ lecture.admin_tel }}</dd>
				<dt>참석 인원</dt>
				<dd>{{ lecture.count }}</dd>
				<dt>비고</dt>
				<dd>{{ lecture.message|escape|linebreaks }}&nbsp;</dd>
				<dt>예약 시작</dt>
				<dd>{{ lecture.start }}</dd>
				<dt>예약 종료</dt>
				<dd>{{ lecture.end }}</dd>
				<dt>예약 강의실</dt>
				<dd>{{ lecture.room.name|escape }}</dd>
			</dl>
		</article>

		{% if user.is_staff or lecture.user == user %}
		<article class="padding">
			<form id="delete" method="post" action="{% url 'lecture:delete' %}" onclick="return confirm('예약을 취소하시겠습니까?')">
				{% csrf_token %}
				<input type="hidden" name="id" value="{{ lecture.id }}">
				<button type="submit">삭제</button>
			</form>
		</article>
		{% endif %}
	</section>

	<script src="{% static 'js/jquery/jquery.js' %}"></script>
	<script src="{% static 'js/tuktuk/tuktuk.js' %}"></script>
	<script src="{% static 'js/jquery-ui/jquery-ui.js' %}"></script>
	<script src="{% static 'js/jquery-ui/jquery-ui-dtpicker.js' %}"></script>
	<script src="{% static 'js/moment/moment.js' %}"></script>
</body>
</html>