webroot/mail/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^write/?$', 'mail.views.write', name='write'),
    url(r'^attachment/(?P<hash>[a-z0-9]+)/?$', 'mail.views.attachment', name='attachment'),
    url(r'^check/(?P<user>[a-z0-9]+)/(?P<mail>[a-z0-9]+)/?$', 'mail.views.check', name='check'),
)

webroot/manager/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    url(r'^$', 'manager.views.index', name='index'),
    url(r'^login/?$', auth_views.login, 
        {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/?$', auth_views.logout,
        {'template_name': 'registration/logout.html'}, name='logout'),

    # User list
    url(r'^userlist/?$', 'manager.views.userlist', name='userlist'),
    url(r'^modify_userlist/?$', 'manager.views.modify_userlist', name='modify_userlist'),

    url(r'^user_profile/(\d+)/?$', 'manager.views.user_profile', name='user_profile'),
    url(r'^convert/?$', 'manager.views.convert', name='convert'),

    # Mail
    url(r'^mail/staff/?$', 'manager.views.mail_staff', name='mail_staff'),
    url(r'^mail/staff/edit/?$', 'manager.views.edit_mail_staff', name='edit_mail_staff'),
    url(r'^mail/check/?$', 'manager.views.mail_check', name='mail_check'),

    # Document

    # Document-index
    url(r'^document/?$', 'manager.views_document.index', name='document_index'),
    url(r'^document/mentoringreport/?$', 'manager.views_document.mentoringreport', name='document_mentoringreport'),
    url(r'^document/mentoringreport/excel/?$', 'manager.views.convert_mentoringreport', name='convert_mentoringreport'),

    # Document - DonationReceipt
    #url(r'^document/donationreceipt/?$', 'manager.views_document.donationreceipt', name='document_donationreceipt'),
    url(r'^document/donationreceipt/create/?$', 'manager.views_document_donationreceipt.create_donationreceipt', name='document_donationreceipt_create'),
    url(r'^document/donationreceipt/report/?$', 'manager.views_document_donationreceipt.donationreceipt_report', name='document_donationreceipt_report'),

    # Notice
    url(r'^notice/$', 'manager.views_notice.list', name='notice'),
    url(r'^notice/(\d+)/$', 'manager.views_notice.detail', name='notice_detail'),
    url(r'^notice/add/$', 'manager.views_notice.add_notice', name='notice_add'),
    url(r'^notice/edit/(\d+)/$', 'manager.views_notice.edit_notice', name='notice_edit'),
    url(r'^notice/category/$', 'manager.views_notice.category_list', name='notice_category'),
    url(r'^notice/category/(\d+)/$', 'manager.views_notice.category_detail', name='notice_category_detail'),
    url(r'^notice/category/edit/(\d+)/$', 'manager.views_notice.edit_category', name='notice_category_edit'),
    url(r'^notice/category/add/$', 'manager.views_notice.add_category', name='notice_category_add'),

    # Lecture
    url(r'^lecture/?$', 'manager.views.lecturelist', name='lecturelist'),
    url(r'^lecture/dashboard/?$', 'manager.views.lecture_dashboard', name='lecture_dashboard'),
    url(r'^lecture/list$', 'manager.views.view_lecturelist', name='lecturelist_view'),
    url(r'^lecture/room/?$', 'manager.views.lectureroom', name='lectureroom'),
    url(r'^lecture/room/remove/?$', 'manager.views.lectureroom_remove', name='lectureroom_remove'),
    url(r'^lecture/block/?$', 'manager.views.lectureblock', name='lectureblock'),
    url(r'^lecture/block/new/?$', 'manager.views.lectureblock_new', name='lectureblock_new'),

    #임시. 나중에 바꿀것
    # url(r'^lecture/?$', 'manager.views.lecturelist', name='lectureblock'),

    url(r'^only_admin', 'manager.views.only_admin', name='only_admin'),
)

webroot/somain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # default admin
    url(r'^django_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^django_admin/', include(admin.site.urls)),

    # structure
    url(r'^$', 'structure.views.main'),
    # url(r'^edit_profile/$', 'structure.views.edit_profile', name='edit_profile'),
    url(r'^check_id/$', 'member.views.check_id', name='check_id'),

    # django-registration
    url(r'^accounts/', include('registration.backends.default.urls')),

    # manager
    url(r'^admin/', include('manager.urls', namespace='manager')),

    # member
    url(r'^member/', include('member.urls', namespace='member')),
    
    # korzip / lecture / mail
    url(r'^korzip/', include('korzip.urls', namespace='korzip')),
    url(r'^lecture/', include('lectureroom.urls', namespace='lecture')),
    url(r'^mail/', include('mail.urls', namespace='mail')),

    # Test
    url(r'^send_mail_test/', 'structure.mail.send_staff_view', name='send_staff'),

    # document
    url(r'^document/', include('document.urls', namespace='document')),

    # Notice
    url(r'^notice/', include('structure.urls_notice', namespace='notice')),

    # Mobile API
    url(r'^mobile/', include('mobile.urls', namespace='mobile')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

webroot/manager/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.utils.html import escape
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

# decorator
from django.contrib.auth.decorators import login_required

# python library
from time import mktime
import calendar
from calendar import monthrange
from datetime import datetime
from datetime import time as dt_time
from datetime import date as dt_date
import time
import re
import json

# member 모델
from member.models import SomaUser
from member.models import Award, Career

# settings.py
from somain.settings import MEDIA_ROOT, MEDIA_URL

# manager 함수
from manager.models import modify_permission, modify_step

# Excel
from tempfile import TemporaryFile
from xlwt import Workbook

# LectureRoom 모델
from lectureroom.models import LectureRoom, LectureBlock, Lecture

# Mail 모델
from mail.models import Mail

# Proejct 모델
from project.models import *

# Document 모델
from document.models import *

# Custom user model
try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

# Log
from log.models import create_log
from log.models import Type as Log_Type

# decorator
from manager.decorator import staff_login_required

# custom functions
from manager.functions import get_strftime


def index(request):
    return redirect('/admin/userlist')


@staff_login_required
def userlist(request):
    users = []
    modify_list = []
    type = request.GET.get('type', '')

    # 멘토/멘티 구분
    if type == 'mentee':
        users = User.objects.filter(type='1').filter(is_approval=True)
        title = '멘티 목록'
        subtitle = ''
        active_li = 'mentee'
    elif type == 'mentor':
        users = User.objects.filter(type='2').filter(is_approval=True)
        title = '멘토 목록'
        subtitle = ''
        active_li = 'mentor'
    elif type == 'staff':
        users = User.objects.filter(type='3').filter(is_approval=True)
        title = '관리자 목록'
        subtitle = ''

    # 멘티 기수 구분
    elif type == 'mentee1':
        users = User.objects.filter(type='1').filter(course_term='1').filter(is_approval=True)
        title = '멘티 (1기) 목록'
        subtitle = ''
        active_li = 'mentee1'

    elif type == 'mentee2':
        users = User.objects.filter(type='1').filter(course_term='2').filter(is_approval=True)
        title = '멘티 (2기) 목록'
        subtitle = ''
        active_li = 'mentee2'

    elif type == 'mentee3':
        users = User.objects.filter(type='1').filter(course_term='3').filter(is_approval=True)
        title = '멘티 (3기) 목록'
        subtitle = ''
        active_li = 'mentee3'

    elif type == 'mentee4':
        users = User.objects.filter(type='1').filter(course_term='4').filter(is_approval=True)
        title = '멘티 (4기) 목록'
        subtitle = ''
        active_li = 'mentee4'


    # 활성/비활성 구분
    elif type == 'approval':
        users = User.objects.filter(is_approval=True)
        title = '활성 사용자 목록'
        subtitle = '사무국에 사용 승인을 받은 사용자 목록입니다'
        active_li = 'approval'
    elif type == 'wait':
        users = User.objects.filter(is_approval=False)
        title = '승인 대기자 목록'
        subtitle = '사무국에 사용 승인을 받기 위해 대기중인 사용자 목록입니다'
        active_li = 'wait'
    else:
        users = User.objects.all()
        title = '전체 사용자 목록'
        subtitle = '승인 사용자, 승인 대기자, 관리자를 포함한 모든 사용자 목록입니다'
        active_li = 'all'

    d = {
        'modify_list': modify_list,
        'title': title,
        'subtitle': subtitle,
        'users': users,
        'active_li': active_li,
        'type': type,
    }

    return render_to_response('manager/userlist.html', d, RequestContext(request))

'''
userlist에서 select의 value값에 따라 submit된 값을 이용,
선택된 유저들을 편집한다

permission: 권한 변경
step: 단계 변경

'''
def modify_userlist(request):
    if request.method == 'POST':
        query_dict = request.POST
        user_list = query_dict.getlist('check_user_id')
        permission = query_dict['permission']
        step = query_dict['step']

        print 'check_user_id:', user_list
        print 'permission', permission

        # 권한 변경
        if permission != '':
            modify_permission(permission, user_list)

            user_text = u'유저 ('
            user_names_text = ''
            for i in range(len(user_list)):
                user = User.objects.get(id=user_list[i])
                name = user.first_name + user.last_name
                if i != len(user_list)-1:
                    user_names_text = user_names_text + name + ', '
                else:
                    user_names_text = user_names_text + name

            user_text = user_text + user_names_text + u')'
            log_text = user_text + u'의 권한 변경(' + permission + ')'

            log_type, exist = Log_Type.objects.get_or_create(title=u'유저 권한 변경')
            log = create_log(user=request.user,
                            type=log_type,
                            text=log_text)
            log.save()

        # 단계 변경
        if step != '':
            modify_step(step, user_list)

            user_text = u'유저 ('
            user_names_text = ''
            for i in range(len(user_list)):
                user = User.objects.get(id=user_list[i])
                name = user.first_name + user.last_name
                if i != len(user_list)-1:
                    user_names_text = user_names_text + name + ', '
                else:
                    user_names_text = user_names_text + name

            user_text = user_text + user_names_text + u')'
            log_text = user_text + u'의 단계 변경(' + step + ')'

            log_type, exist = Log_Type.objects.get_or_create(title=u'유저 단계 변경')
            log = create_log(user=request.user,
                            type=log_type,
                            text=log_text)
            log.save()

        return redirect('manager:userlist')
    else:
        return redirect('manager:userlist')

def convert(request):
    if request.method == 'POST':
        query_dict = request.POST
        user_id_list = query_dict.getlist('user_id')

        users = []
        for user_id in user_id_list:
            user = SomaUser.objects.get(id=user_id)
            if not user.type.title == u'관리자' or user.type.title == u'시스템 관리자':
                users.append(user)

        file_src = convert_excel(users)
        d = {
            'file_src': file_src,
        }

        data = open(file_src).read()
        resp = HttpResponse(data, content_type='application/x-download')
        resp['Content-Disposition'] = 'attachment;filename=convert.xls'
        return resp
    # return render_to_response("manager/convert_result.html", d)

def convert_excel(users):
    print 'convert_excel, users:', users
    start_row = 3
    start_column = 1

    book = Workbook()
    sheet1 = book.add_sheet('Users')

    info_title_list = [
        u'타입',
        u'상태',
        u'단계',
        u'아이디',
        u'이름',
        u'이메일',
        u'나이',
        u'성별',
        u'생일',
        u'주민등록번호',
        u'집 전화번호',
        u'휴대전화 번호',
        u'학력',
        u'병역',
        u'학교',
        u'주소',
        u'우편번호',
        u'구글 계정',
        u'트위터 계정',
        u'페이스북 계정',
    ]

    for i in range(len(info_title_list)):
        info_title = info_title_list[i]
        sheet1.write(start_row, start_column+i, info_title)

    for i in range(len(users)):
        user = users[i]
        print user

        type = user.type.title
        if user.type.title == u'멘티':
            type = type + "(" + user.course_term.title + user.course_step.title + ")"
        #elif user.type.title == u'관리자':
        #    continue
        #elif user.type.title == u'시스템 관리자':
        #    continue
        status = user.course_status.title
        step = user.course_step.title
        user_id = user.username
        name = user.last_name + user.first_name
        email = user.email
        age = user.age
        gender = user.get_gender_display()
        birthday = user.birthday.strftime("%Y-%m-%d")
        rr_number = user.rr_number
        home_number = user.home_number
        phone_number = user.phone_number
        education_level = user.education_level.title
        military = user.military.title
        school = user.school
        address = user.address1 + user.address2
        zipcode = user.zipcode
        google = user.google
        twitter = user.twitter
        facebook = user.facebook

        user_info_list = [
            type,
            status,
            step,
            user_id,
            name,
            email,
            age,
            gender,
            birthday,
            rr_number,
            home_number,
            phone_number,
            education_level,
            military,
            school,
            address,
            zipcode,
            google,
            twitter,
            facebook
        ]

        for j in range(len(user_info_list)):
            info = user_info_list[j]
            sheet1.write(start_row+1+i, start_column+j, info)

    #now = datetime.now().strftime("%Y-%m-%d.%H:%M:%S"),

    filename = "convert/" + 'user' + "abc" + ".xls"
    book.save(MEDIA_ROOT + "/" + filename)
    book.save(TemporaryFile())

    return MEDIA_ROOT + "/" + filename


def convert_mentoringreport(request):
    print 'convert_mentoringreport'
    if request.method == 'POST':
        query_dict = request.POST
        print query_dict
        document_id_list = query_dict.getlist('document_id')
        print document_id_list

        docs = []
        for doc_id in document_id_list:
            doc = MentoringReport.objects.get(id=doc_id)
            docs.append(doc)

        file_src = mentoringreport_excel(docs)

webroot/templates/manager/notice/add.html
{% extends 'manager/notice/base.html' %}
{% load staticfiles %}

{% block content_notice %}
<legend>공지사항 추가</legend>
<div class="row-fluid">
	<form class="form-horizontal" method="post">{% csrf_token %}
		{% for field in form %}
		<div class="control-group">
			<label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
			<div class="controls">
				{{ field }}
			</div>
		</div>
		{% endfor %}
		<div class="span10 offset2">
			<input type="submit" class="btn btn-medium btn-orange" value="작성완료"/>
		</div>
	</form>
</div>
{% endblock %}

{% block bottom %}
<script src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'js/ckeditor/adapters/jquery.js' %}"></script>
<script>
$('#{{ form.content.id_for_label }}').ckeditor({
	enterMode : CKEDITOR.ENTER_BR,
	shiftEnterMode: CKEDITOR.ENTER_P
});
</script>
{% endblock %}

webroot/templates/manager/notice/base.html
{% extends 'manager/base.html' %}
{% load staticfiles %}

{% block title %}{{ title }}{% endblock %}

<!-- 현재 선택된 sidebar 메뉴일 경우 active -->
{% block sidebar_group_notice_class %}active{% endblock %}

<!-- 
    아래 두 목록이 
    toggle은 collapsed, collapse는 공백 : 접혀진상태
    toggle은 공백, collapse는 in : 펴진 상태
-->
{% block sidebar_toggle_notice_class %}{% endblock %}
{% block sidebar_collapse_notice_class %}in{% endblock %}

<!-- li클래스 active여부. 검은색으로 좀 더 진하게 표시됨 -->
{% block sidebar_li_notice_list_class %}
{% if active_li == 'list' %}active{% endif %}
{% endblock %}

{% block sidebar_li_notice_add_class %}
{% if active_li == 'add' %}active{% endif %}
{% endblock %}

{% block sidebar_li_notice_category_list_class %}
{% if active_li == 'category_list' %}active{% endif %}
{% endblock %}

{% block sidebar_li_notice_category_add_class %}
{% if active_li == 'category_add' %}active{% endif %}
{% endblock %}


{% block head %}
{% endblock %}
{% block content %}


<div class="content container-fluid">
	<section class="widget">
		<div>
			{% block content_notice %}
			{% endblock %}
		</div>
	</section>
</div>

{% endblock %}


{% block bottom_script %}
<!-- jquery and friends -->
<script src="{% static 'js/jquery/jquery.js' %}"></script>

<!-- jquery plugins -->
<script src="{% static 'js/jquery/jquery.maskedinput.js' %}"></script>
<script src="{% static 'js/parsley/parsley.js' %}"></script>
<script src="{% static 'js/jquery/jquery.uniform.js' %}"></script>
<script src="{% static 'js/jquery/jquery.select2.js' %}"></script>
<script src="{% static 'js/jquery/jquery.datatable.js' %}"></script>

<!--backbone and friends -->
<script src="{% static 'js/backbone/underscore-min.js' %}"></script>
<script src="{% static 'js/backbone/backbone-min.js' %}"></script>
<script src="{% static 'js/backbone/backbone-pageable.js' %}"></script>
<script src="{% static 'js/backgrid/backgrid.js' %}"></script>
<script src="{% static 'js/backgrid/backgrid-paginator.js' %}"></script>

<!-- bootstrap default plugins -->
<script src="{% static 'js/bootstrap/bootstrap-transition.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-collapse.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-alert.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-tooltip.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-popover.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-button.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-dropdown.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-modal.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap-tab.js' %}"></script>

<!-- basic application js-->
<script src="{% static 'js/bootstrap/app.js' %}"></script>
<script src="{% static 'js/bootstrap/settings.js' %}"></script>

<!-- page-specific js -->
<script src="{% static 'js/admin/tables-dynamic.js' %}"></script>
<script src="{% static 'js/forms-elemets.js' %}"></script>
{% endblock %}

{% block after_script %}
{% endblock %}

webroot/templates/manager/notice/category_add.html
{% extends 'manager/notice/base.html' %}
{% load staticfiles %}

{% block content_notice %}
<legend>카테고리 추가</legend>
<div class="row-fluid">
	<form class="form-horizontal" method="post">{% csrf_token %}
		{% for field in form %}
		<div class="control-group">
			<label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
			<div class="controls">
				{{ field }}
			</div>
		</div>
		{% endfor %}
		<div class="span10 offset2">
			<input type="submit" class="btn btn-medium btn-orange" value="작성완료"/>
		</div>
	</form>
</div>
{% endblock %}

{% block bottom %}
<script src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'js/ckeditor/adapters/jquery.js' %}"></script>
<script>
$('#{{ form.content.id_for_label }}').ckeditor({
	enterMode : CKEDITOR.ENTER_BR,
	shiftEnterMode: CKEDITOR.ENTER_P
});
</script>
{% endblock %}

webroot/templates/manager/notice/category_detail.html
{% extends 'manager/notice/base.html' %}

{% block content_notice %}
<legend>{{ category.title }}</legend>
<div>
	우선순위 : {{ category.priority }}
</div>
{% endblock %}

webroot/templates/manager/notice/category_edit.html
{% extends 'manager/notice/base.html' %}
{% load staticfiles %}

{% block content_notice %}
<legend>카테고리 수정</legend>
<div class="row-fluid">
	<form class="form-horizontal" method="post">{% csrf_token %}
		{% for field in form %}
		<div class="control-group">
			<label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
			<div class="controls">
				{{ field }}
			</div>
		</div>
		{% endfor %}
		<div class="span10 offset2">
			<input type="submit" class="btn btn-medium btn-orange" value="작성완료"/>
		</div>
	</form>
</div>
{% endblock %}

{% block bottom %}
<script src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'js/ckeditor/adapters/jquery.js' %}"></script>
<script>
$('#{{ form.content.id_for_label }}').ckeditor({
	enterMode : CKEDITOR.ENTER_BR,
	shiftEnterMode: CKEDITOR.ENTER_P
});
</script>
{% endblock %}

webroot/templates/manager/notice/category_list.html
{% extends 'manager/notice/base.html' %}

{% block content_notice %}
<legend>공지사항 카테고리 목록</legend>
<div>
	{% for category in categories %}
	<div class="row-fluid" style="margin-bottom: 5px;">

		<span class="span8">
			<span class="btn">우선순위 : {{ category.priority }}</span>
			<span>&nbsp;&nbsp;&nbsp;<a href="{% url 'manager:notice_category_detail' category.id %}">{{ category.title }}</a></span>
		</span>
		<span class="span3" style="text-align: right; padding-right: 50px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'manager:notice_category_edit' category.id %}"><span class="btn btn-info">수정</span></a></span>
	</div>
	{% endfor %}
</div>


{% endblock %}

webroot/templates/manager/notice/detail.html
{% extends 'manager/notice/base.html' %}

{% block content_notice %}
<legend>{{ notice.title }} <small> {{ notice.created|date:'Y-m-d' }}</small></legend>
<div>
	{{ notice.content }}
</div>
{% endblock %}

webroot/templates/manager/notice/edit.html
{% extends 'manager/notice/base.html' %}
{% load staticfiles %}

{% block content_notice %}
<legend>공지사항 추가</legend>
<div class="row-fluid">
	<form class="form-horizontal" method="post">{% csrf_token %}
		{% for field in form %}
		<div class="control-group">
			<label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
			<div class="controls">
				{{ field }}
			</div>
		</div>
		{% endfor %}
		<div class="span10 offset2">
			<input type="submit" class="btn btn-medium btn-orange" value="작성완료"/>
		</div>
	</form>
</div>
{% endblock %}

{% block bottom %}
<script src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'js/ckeditor/adapters/jquery.js' %}"></script>
<script>
$('#{{ form.content.id_for_label }}').ckeditor({
	enterMode : CKEDITOR.ENTER_BR,
	shiftEnterMode: CKEDITOR.ENTER_P
});
</script>
{% endblock %}

webroot/templates/manager/notice/list.html
{% extends 'manager/notice/base.html' %}

{% block head %}
{% endblock %}

{% block content_notice %}
<div class="row-fluid">
	<span class="span10">
		<legend>공지사항 목록</legend>
	</span>
	<span class="span2" style="text-align: right; margin-top: 10px;">
		<select placeholder="카테고리 선택" id="category_select" class="chzn-select span12" name="category">
			<option value=""></option>
			{% for category in categories %}
			<option value="{{ category.id }}">{{ category.title }}</option>
			{% endfor %}
		</select>
	</span>
</div>
<div>
	{% for notice in notices %}
	<div class="row-fluid" style="margin-bottom: 5px;">
		<span class="span1">{{ notice.category.title }}</span>
		<span class="span8">
			&nbsp;&nbsp;&nbsp;<a href="{% url 'manager:notice_detail' notice.id %}">{{ notice.title }}</a>
		</span>
		<span class="span3" style="text-align: right; padding-right: 0px;">|&nbsp;&nbsp;{{ notice.created|date:'Y-m-d' }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'manager:notice_edit' notice.id %}"><span class="btn btn-info">수정</span></a></span>
	</div>
	{% endfor %}
</div>



{% endblock %}