webroot/document/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    url(r'^$', 'document.views.index', name='index'),
    url(r'^sign/(\d+)/?$', 'document.views.sign', name='sign'),
    url(r'^submit/(\d+)/?$', 'document.views.submit', name='submit'),
    url(r'^view/(\d+)/?$', 'document.views.document_view', name='view'),

    url(r'^mentoring_report/write/choose/?$', 'document.views.mentoring_report_write_choose', name='mentoring_report_write_choose'),
    url(r'^mentoring_report/write/(\d+)/?$', 'document.views.mentoring_report_write', name='mentoring_report_write'),
    url(r'^mentoring_report_list/?$', 'document.views.mentoring_report_list', name='mentoring_report_list'),
    url(r'^mentoring_report/(\d+)/?$', 'document.views.mentoring_report_view', name='mentoring_report_view'),

    url(r'^donationreceipt/write/(\d+)/?$', 'document.views.donationreceipt_write', name='donationreceipt_write'),
    url(r'^donationreceipt/(\d+)/?$', 'document.views.donationreceipt_view', name='donationreceipt_view'),
)

webroot/mail/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^write/?$', 'mail.views.write', name='write'),
    url(r'^attachment/(?P<hash>[a-z0-9]+)/?$', 'mail.views.attachment', name='attachment'),
    url(r'^check/(?P<user>[a-z0-9]+)/(?P<mail>[a-z0-9]+)/?$', 'mail.views.check', name='check'),
)

webroot/somain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # default admin
    url(r'^django_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^django_admin/', include(admin.site.urls)),

    # structure
    url(r'^$', 'structure.views.main'),
    # url(r'^edit_profile/$', 'structure.views.edit_profile', name='edit_profile'),
    url(r'^check_id/$', 'member.views.check_id', name='check_id'),

    # django-registration
    url(r'^accounts/', include('registration.backends.default.urls')),

    # manager
    url(r'^admin/', include('manager.urls', namespace='manager')),

    # member
    url(r'^member/', include('member.urls', namespace='member')),
    
    # korzip / lecture / mail
    url(r'^korzip/', include('korzip.urls', namespace='korzip')),
    url(r'^lecture/', include('lectureroom.urls', namespace='lecture')),
    url(r'^mail/', include('mail.urls', namespace='mail')),

    # Test
    url(r'^send_mail_test/', 'structure.mail.send_staff_view', name='send_staff'),

    # document
    url(r'^document/', include('document.urls', namespace='document')),

    # Notice
    url(r'^notice/', include('structure.urls_notice', namespace='notice')),

    # Mobile API
    url(r'^mobile/', include('mobile.urls', namespace='mobile')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

webroot/document/forms.py
#-*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms

from project.models import *
from document.models import MentoringReport
from document.models import DonationReceipt

from django.contrib.admin import widgets


textinput_mini = {
    'class': 'input-mini',
}
textinput_small = {
    'class': 'input-small',
}
textinput_large = {
    'class': 'input-large',
}
textinput_xlarge = {
    'class': 'input-xlarge',
}
textinput_xxlarge = {
    'class': 'input-xxlarge',
}

textarea_big = {
    'class': 'span8',
    'rows': 10,
}
textarea_mid = {
    'class': 'span8',
    'rows': 5,
}
textarea_small = {
    'class': 'span8',
    'rows': 3,
}
select = {
    'class': "chzn-select",
}
class MentoringReportForm(forms.ModelForm):

    class Meta:
        model = MentoringReport
        exclude = ['mentor', 'project', 'doc_title', 'is_complete', 'complete_time', 'submit_time', 'is_submitted', 'sign_users', 'submit_user', 'deadline', 'real_time', 'accept_time']

        widgets = {
            'type': forms.RadioSelect(),
            'mentees': forms.CheckboxSelectMultiple(),
            'title': forms.TextInput(attrs=textinput_xxlarge),
            'content': forms.Textarea(attrs=textarea_big),
            'opinion': forms.Textarea(attrs=textarea_mid),
            'schedule': forms.Textarea(attrs=textarea_small),
            'issue': forms.Textarea(attrs=textarea_small),
        }

class DonationReceiptForm(forms.ModelForm):

    class Meta:
        model = DonationReceipt
        exclude = ['doc_title', 'is_complete', 'complete_time', 'submit_time', 'is_submitted', 'sign_users', 'submit_user', 'user', 'address']

        widgets = {
            'year': forms.TextInput(attrs=textinput_mini),
            'month': forms.TextInput(attrs=textinput_mini),
        }

webroot/document/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.contrib import messages

from datetime import datetime, time, timedelta

from project.models import Project, ProjectType

from document.models import Document, Sign
from document.models import DonationReceipt
from document.models import MentoringType, MentoringReport
from document.forms import MentoringReportForm, DonationReceiptForm

# Custom user model
try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

from dateutil.relativedelta import relativedelta
from datetime import datetime, time, timedelta
from nptime import nptime

from somain.settings import MEDIA_ROOT, MEDIA_URL

# mktime 써보기
def get_time_seconds(time):
    hour = time.hour
    minute = time.minute
    second = time.second

    return (3600*hour + 60*minute + second)


def get_real_time(start_time, end_time):
    hour = end_time.hour - start_time.hour
    minute = end_time.minute - start_time.minute
    time = hour*60 + minute

    return time

def get_accept_time(start_time, end_time):
    start_second = get_time_seconds(start_time)
    end_second = get_time_seconds(end_time)

    total_second = end_second - start_second
    thirty_minute_number = total_second / 1800

    hour = 0
    minute = 0

    while thirty_minute_number > 1:
        thirty_minute_number = thirty_minute_number - 2
        hour = hour + 1

    minute = thirty_minute_number * 30

    time = hour*60 + minute

    return time

def get_strftime(minute):
    hour = 0
    while minute >= 60:
        hour = hour + 1
        minute = minute - 60

    return '%s:%s' % (str(hour).zfill(2), str(minute).zfill(2))


# 온라인 서류제출 메인
def index(request):
    user = request.user

    require_sign_documents = []
    docs = user.document_by_sign_user.filter(is_complete=False)
    require_submit_documents = user.document_by_sign_user.filter(is_complete=True).filter(is_submitted=False)
    recent_submit_documents = user.document_by_sign_user.filter(is_complete=True).filter(is_submitted=True).order_by('-submit_time')[:5]
    for doc in docs:
        if doc.sign_by_document.filter(user=user).exists():
            pass
        else:
            require_sign_documents.append(doc)
    d = {
        'user': user,
        'require_sign_documents': require_sign_documents,
        'require_submit_documents': require_submit_documents,
        'recent_submit_documents': recent_submit_documents,
    }

    return render_to_response('document/index.html', d, RequestContext(request))

def sign(request, document_id):
    user = request.user
    all_signed = True
    document = Document.objects.get(id=document_id).get_document()
    user_is_signed = document.sign_by_document.filter(user=user).exists()
    sign_users = document.sign_users.all()
    sign_infos = []

    # 서명해야할 사용자와 각 사용자의 서명여부 전달
    for sign_user in sign_users:
        sign_user_signed = document.sign_by_document.filter(user=sign_user).exists()
        if not sign_user_signed:
            all_signed = False

        sign_data = {
            'user': sign_user,
            'is_signed': document.sign_by_document.filter(user=sign_user).exists(),
            'all_signed': all_signed,
        }
        sign_infos.append(sign_data)

    # all_signed라면 document의 is_complete를 바꾸어준다
    if all_signed:
        document.is_complete = True
        document.save()


    # 서류 종류에 따라 다르게 데이터 전달
    if document.doc_title == u'멘토링 보고서':
        data = {
            u'구분': document.type,
            u'프로젝트': document.project,
            u'멘토링 날짜': document.date,
            u'장소': document.place,
            u'멘토링 주제': document.title,
            u'멘토링 내용': document.content,
        }
    elif document.doc_title == u'지출 계획서':
        pass

    # 전달할 데이터
    d = {
        'user': user,
        'user_is_signed': user_is_signed,
        'document': document,
        'sign_infos': sign_infos,
        'data': data,
    }

    # POST방식일 땐 서명정보를 생성 및 저장 후 페이지 로드
    if request.method == 'POST':
        Sign.objects.filter(user=request.user, document=document).delete()
        cur_sign = Sign(user=request.user, document=document)
        cur_sign.save()
        # 메시지 전달
        messages.add_message(request, messages.SUCCESS, document.doc_title)
        return redirect('document:sign', document_id)

    else:
        return render_to_response('document/sign.html', d, RequestContext(request))


def submit(request, document_id):
    user = request.user
    document = Document.objects.get(id=document_id)
    if document.is_complete == False:
        return HttpResponse('서명이 완료되지않음')

    try:
        document.is_submitted = True
        document.submit_time = datetime.today()
        document.submit_user = user
        document.save()
        messages.add_message(request, messages.SUCCESS, u'제출 완료')
        print u'제출완료'
    except:
        messages.add_message(request, messages.ERROR, u'제출에 실패')
        print u'제출실패'

    return redirect(request.META['HTTP_REFERER'])


def document_view(request, document_id):
    # print request
    user = request.user
    document = Document.objects.get(id=document_id).get_document()
    if document.doc_title == u'멘토링 보고서':
        return redirect('document:mentoring_report_view', document.id)
    elif document.doc_title == u'기부금 영수증':
        return redirect('document:donationreceipt_view', document.id)
    else:
        return HttpResponse(u'미지원 문서 뷰 타입입니다')


# 멘토만 가능, 작성 전 프로젝트를 선택하도록 함
def mentoring_report_write_choose(request):
    user = request.user
    manage_projects = user.project_by_mentor.filter(is_finished=False)
    projects = Project.objects.filter(is_finished=False)

    d = {
        'manage_projects': manage_projects,
        'projects': projects,
    }

    return render_to_response('document/mentoring_report_choose.html', d, RequestContext(request))


def get_timedelta(time):
    return timedelta(hours=time.hour, minutes=time.minute)

def get_timedelta_minus(time):
    return timedelta(hours=-time.hour, minutes=-time.minute)

# 멘토만 가능하도록 데코레이터
def mentoring_report_write(request, project_id):
    user = request.user
    project = Project.objects.get(id=project_id)

    if request.method == 'POST':
        #form.mentees.queryset = User.objects.filter()
        form = MentoringReportForm(request.POST, initial={'project': project})

        if form.is_valid():
            print form.cleaned_data
            start_time = form.cleaned_data['start_time']
            end_time = form.cleaned_data['end_time']
            #print form.cleaned_data['mentees']
            print type(start_time)
            print type(end_time)

            obj = form.save(commit=False)
            # 실제시간과 인정시간 입력
            #obj.real_time = end_time - relativedelta(hours=start_time.hour, minutes=start_time.minute)
            #obj.accept_time = end_time - relativedelta(hours=start_time.hour, minutes=start_time.minute)
            #obj.real_time = time(2,0)
            #obj.accept_time = time(2,0)
            obj.real_time = nptime(end_time.hour, end_time.minute) + timedelta(hours=-start_time.hour, minutes=-start_time.minute)
            obj.accept_time = nptime(end_time.hour, end_time.minute) + timedelta(hours=-start_time.hour, minutes=-start_time.minute)

            #print 'accept_time:', obj.accept_time
            #print 'obj.accept_time > nptime(4, 0):', obj.accept_time > nptime(4, 0)
            if obj.accept_time > nptime(4, 0):
                obj.accept_time = nptime(4, 0)
                print obj.accept_time

            # 프로젝트지정
            #type(form.cleaned_data['project_id'])
            #project_id = int(form.cleaned_data['project_id'])
            #type(project_id)
            project = Project.objects.get(id=project_id)
            obj.project = project

            #print 'debug1'
            # 제출기한시간 입력
            d1 = datetime.today()
            d2 = d1.replace(day=d1.day+1, hour=18, minute=0, second=0)
            obj.deadline = d2
            #print 'debug2'
            #print obj

            obj.save()
            #print type(obj)
            #print obj.sign_users
            #print 'debug3'

            # 유저 멘토여부 검사
            mentor = request.user
            if mentor.type.title != u'멘토':
                return HttpResponse(mentor + u'는 멘토가 아닙니다')
            else:
                obj.mentor = mentor

            ''' 아래 2개 한번에 실행 '''
            ''' 참여 연수생 정보를 다시 저장 '''
            ''' 서명이 필요한 사용자에 프로젝트의 멘토와 참여 멘티들을 추가해서 저장한다 '''
            #print form.cleaned_data['project'].mentor
            #print type(form.cleaned_data['project'].mentor)
            #mentor_id = form.cleaned_data['mentor_id']
            obj.sign_users.add(mentor)
            for mentee in form.cleaned_data['mentees'].all():
                obj.mentees.add(mentee)
                obj.sign_users.add(mentee)
            obj.save()

            # GCM 전송
            from mobile.api import send_gcm
            reg_id_list = [user.android_registration_id for user in obj.sign_users.all()]
            data = {
                'document': obj.json(),
            }
            send_gcm(reg_id_list, data)

            return redirect('document:index')
        else:
            return render_to_response('document/mentoring_report_write.html', {'form': form,}, RequestContext(request))
    else:
        initial_data = {
            'type': MentoringType.objects.get(title=u'정규'),
            'project': project,
        }
        form = MentoringReportForm(initial=initial_data)
        form.fields['type'].empty_label = None
        #form.fields['project'].queryset = Project.objects.filter(id=project_id)
        #form.fields['cooperation_mentor'].queryset = User.objects.filter(type__title=u'멘토')
        form.fields['mentees'].help_text = None

webroot/templates/document/donationreceipt_write.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}멘토링 보고서 작성{% endblock %}

{% block head %}
<style>
textarea {
	/*width: 600px;*/
}
</style>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row-fluid">
		<h3>멘토링 보고서 작성 <small>멘토링 보고서를 작성하실 수 있습니다</small></h3>

		<div class="span8 offset1">
			<legend>{{ project.title }} 프로젝트 / {{ mentor.last_name }}{{ mentor.first_name }} 멘토</legend>
		<form class="form-horizontal label-left" novalidate="novalidate" method="POST" enctype="multipart/form-data" data-validate="parsley">{% csrf_token %}

			<input type="hidden" name="project_id" value="{{ project.id }}"/>
			<input type="hidden" name="mentor_id" value="{{ mentor.id }}"/>
			{% for field in form %}
			<div class="control-group">
				<label for="{{ field.id_for_label }}" class="control-label">
					{{ field.label }}
				</label>
				<div class="controls controls-row">
					{{ field }}
					<span class="help-inline">
						{{ field.help_text }}
						{{ field.errors }}
					</span>
				</div>
			</div>
			{% endfor %}

			<div class="control-group">
				<label class="control-label">
				</label>
				<div class="controls controls-row">
					<input type="submit" class="btn btn-primary span6" value="작성 완료"/>
				</div>
			</div>
			

		</form>
	</div>
	</div>

</div>
{% endblock %}

{% block bottom %}>
{% endblock %}

webroot/templates/document/index.html
{% extends 'base.html' %}

{% block title %}온라인 서류제출{% endblock %}
{% block page_title %}온라인 서류제출{% endblock %}

{% block head %}
<style>
#submit_sections > section > .section > .title {
	font-weight: bold;
	font-size: 10pt;
	height: 30px;
	line-height: 30px;
}
#submit_sections > section > .section > .button {
	
}

#sign_sections > section {
	margin-bottom: 30px;
}
#sign_sections > section > .section {
	margin-bottom: 0px;
}
#sign_sections > section > .section > .title {
	font-size: 8pt;
	height: 20px;
	line-height: 20px;
}
#sign_sections > section > .section > .button {
	text-align: right;
}
#sign_sections > section > .section > .title > .btn {
	
}

</style>
{% endblock %}

{% block content %}
		<br><br>
<div class="container">
	<div class="row-fluid">
		<div id="submit_sections" class="span5" style="margin-bottom: 100px;">
			<section>
				<legend>MENTORING &nbsp;<a><i class="icon-angle-right"></i></a></legend>
				<div class="row-fluid section">
					<div class="span7 title">멘토링 보고서</div>
					<div class="span5 button">
						<a href="{% url 'document:mentoring_report_list' %}" class="span8 btn btn-dark btn-edge">제출서류 확인</a>
						{% if user.type.title == '멘토' %}
						<a href="{% url 'document:mentoring_report_write_choose' %}" class="span4 btn btn-dark btn-edge">작성</a>
						{% endif %}
					</div>
				</div>
				<div class="row-fluid section">
					<div class="span7 title">프로젝트 활동비 지출 계획서</div>
					<div class="span5 button">
						<a class="span8 btn btn-dark btn-edge">제출서류 확인</a>
						<a class="span4 btn btn-dark btn-edge">작성</a>
					</div>
				</div>
				<div class="row-fluid section">
					<div class="span7 title">회의록</div>
					<div class="span5 button">
						<a class="span8 btn btn-dark btn-edge">제출서류 확인</a>
						<a class="span4 btn btn-dark btn-edge">작성</a>
					</div>
				</div>
			</section>

			<section>
				<legend>COURSE &nbsp;<a><i class="icon-angle-right"></i></a></legend>
				<div class="row-fluid section">
					<ul class="no-style">
						<li>동적으로 생성(관리자가 생성 시 이용자별로 생성)</li>
						<li>ex) (기한 10/03) 10월 기부금 영수증 [7일 남음]</li>
					</ul>
				</div>
			</section>
			
		</div>

		<div id="sign_sections" class="span4 offset2">
			<section>
				<table class="table">
					<caption class="right">서명해야할 서류 <a><i class="icon-angle-right"></i></a></caption>
					<thead>
						<tr>
							<th width="30%">기한</th>
							<th width="40%">타입</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for doc in require_sign_documents %}
						<tr>
							<td>{{ doc.deadline|date:'m/d H:i' }}</td>
							<td>{{ doc.doc_title }}</td>
							<td>
								<a class="btn btn-mini btn-dark btn-edge" href="{% url 'document:view' doc.id %}">보기</a>
								<a class="btn btn-mini btn-dark btn-edge" href="{% url 'document:sign' doc.id %}">서명</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</section>

			<section>
				<table class="table">
					<caption class="right">최근 제출 서류 <a><i class="icon-angle-right"></i></a></caption>
					<thead>
						<tr>
							<th width="30%">제출 일시</th>
							<th width="40%">타입</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for doc in recent_submit_documents %}
						<tr>
							<td>{{ doc.deadline|date:'m/d H:i' }}</td>
							<td>{{ doc.doc_title }}</td>
							<td>
								<a class="btn btn-mini btn-dark btn-edge" href="{% url 'document:view' doc.id %}">보기</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</section>
		</div>
	</div>
</div>

{% endblock %}

webroot/templates/document/mentoring_report_choose.html
{% extends 'base.html' %}

{% block title %}멘토링 보고서 작성{% endblock %}
{% block page_title %}멘토링 보고서 작성{% endblock %}
{% block page_subtitle %}멘토링 보고서를 작성하실 프로젝트를 선택해주세요.{% endblock %}

{% block content %}
<div class="container">
	<div class="row-fluid">
		<a href="{% url 'document:index' %}"><i class="icon-chevron-left"></i> 온라인 서류제출 메인 페이지로 가기</a>
	</div>

	<legend class="no-border no-margin w80">담당 프로젝트</legend>
	<table class="table w80 btn-depend">
		<thead>
			<tr>
				<th width="25%">프로젝트명</th>
				<th>참여 멘티</th>
				<th width="20%"></th>
			</tr>
		</thead>
		<tbody>
		{% for project in manage_projects %}
		<tr>
			<td>{{ project.title }}</td>
			<td>
				{% for mentee in project.mentees.all %}
					{{ mentee.last_name }}{{ mentee.first_name }}{% if forloop.counter != project.mentees.all.count %},{% endif %}
				{% endfor %}
			</td>
			<td><a class="btn btn-dark btn-edge" href="{% url 'document:mentoring_report_write' project.id %}">작성하기</a></td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
	<br><br><br><br>
	<legend class="no-border no-margin w80">전체 프로젝트</legend>
	<table class="table w80 btn-depend">
		<thead>
			<tr>
				<th width="25%">프로젝트명</th>
				<th>참여 멘티</th>
				<th width="20%"></th>
			</tr>
		</thead>
		<tbody>
		{% for project in projects %}
		<tr>
			<td>{{ project.title }}</td>
			<td>
				{% for mentee in project.mentees.all %}
					{{ mentee.last_name }}{{ mentee.first_name }}{% if forloop.counter != project.mentees.all.count %},{% endif %}
				{% endfor %}
			</td>
			<td><a class="btn btn-dark btn-edge" href="{% url 'document:mentoring_report_write' project.id %}">작성하기</a></td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

webroot/templates/document/mentoring_report_list.html
{% extends 'base.html' %}

{% block title %}제출한 멘토링 보고서{% endblock %}
{% block page_title %}제출한 멘토링 보고서{% endblock %}
{% block page_subtitle %}참가한 프로젝트별로 보고서를 분류하여 보여줍니다.{% endblock %}

{% block content %}
<div class="container">
	{% for project in projects %}
	<div class="row-fluid section">
		<legend class="no-border center">{{ project.title }}</legend>
		<table class="table w80 btn-depend">
			<thead>
				<tr>
					<th width="15%">제출 현황</th>
					<th>일시</th>
					<th>장소</th>
					<th>참여멘티</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			{% for report in project.mentoring_report_by_project.all %}
				<tr>
					<td>
						<span class="btn btn-edge {% if report.is_complete == True %}{% else %}btn-inverse{% endif %}" style="font-size: 8pt">
						{% if report.is_complete == True and report.is_submitted == False %}
							작성 완료
						{% elif report.is_submitted == True %}
							제출 완료
						{% else %}
							서명 미완료
						{% endif %}
						</span>
					</td>
					<td>{{ report.date|date:'Y-m-d' }}</td>
					<td>{{ report.place }}</td>
					<td>{% for mentee in report.mentees.all %}
						{{ mentee.last_name }}{{ mentee.first_name }}{% if forloop.counter != report.mentees.all.count %},{% endif %}
						{% endfor %}</td>
					<td>
						<a href="{% url 'document:mentoring_report_view' report.id %}" class="btn btn-edge btn-dark">보기</a>
						<a class="btn btn-edge btn-dark">수정</a>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
	{% endfor %}

	<div class="row-fluid">
		<a href="{% url 'document:index' %}" class="float-right"><i class="icon-chevron-left"></i> 온라인 서류제출 메인 페이지로 가기</a>
	</div>
</div>
{% endblock %}

webroot/templates/document/mentoring_report_write.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}멘토링 보고서 작성{% endblock %}
{% block page_title %}멘토링 보고서 작성{% endblock %}
{% block page_subtitle %}멘토링 보고서를 작성하실 수 있습니다.{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="row-fluid">
		<a href="javascript:history.go(-1)"><i class="icon-chevron-left"></i> 전체 보고서 목록으로 가기</a>
	</div>
	<div class="row-fluid">
		<div class="span8 offset1">
			<legend>{{ project.title }} 프로젝트 | {{ mentor.last_name }}{{ mentor.first_name }} 멘토</legend>
		<form class="form-horizontal label-left" novalidate="novalidate" method="POST" enctype="multipart/form-data" data-validate="parsley">{% csrf_token %}

			<input type="hidden" name="project_id" value="{{ project.id }}"/>
			<input type="hidden" name="mentor_id" value="{{ mentor.id }}"/>
			{% for field in form %}
			<div class="control-group">
				<label for="{{ field.id_for_label }}" class="control-label left">
					{{ field.label }}
				</label>
				<div class="controls controls-row">
					{{ field }}
					<span class="help-inline">
						{{ field.help_text }}
						{{ field.errors }}
					</span>
				</div>
			</div>
			{% endfor %}

			<div class="control-group">
				<label class="control-label">
				</label>
				<div class="controls controls-row">
					<input type="submit" class="btn btn-primary span6" value="작성 완료"/>
				</div>
			</div>
			

		</form>
	</div>
	</div>

</div>
{% endblock %}

{% block bottom %}>
{% endblock %}

webroot/templates/document/sign.html
{% extends 'base.html' %}

{% block title %}ABC{% endblock %}

{% block head %}
<style>
#submit_sections > section > .section > .title {
	font-weight: bold;
	font-size: 10pt;
	height: 30px;
	line-height: 30px;
}
#submit_sections > section > .section > .button {

}

#sign_sections > section > .section > .title {
	font-weight: bold;
	font-size: 10pt;
	height: 30px;
	line-height: 30px;
}

</style>
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %}
<script language="javascript">
window.onload = function(){
	$('#success_modal').modal('show');
}
</script>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

{% block content %}
<div id="success_modal" style="margin-top: 150px;" class="modal styled hide fade" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
	<div class="modal-body" style="text-align: center; height: 50px; line-height: 50px;">
		<span>서명이 완료되었습니다</span>
	</div>
	<div class="modal-footer" style="height: 20px;">
		<div style="text-align: center;">
			<a href="#" data-dismiss="modal" class="btn">닫기</a>
		</div>
	</div>
</div>


<div class="container">
	<div class="row-fluid">
		<a href="{% url 'document:index' %}" class="btn btn-orange"><i class="icon-chevron-left"></i>온라인 서류제출 메인 페이지로</a>
	</div>
	<div class="row-fluid">
		<h3>온라인 서류 서명</h3>
	</div>
	<div class="row-fluid">
		<div id="submit_sections" class="span7" style="margin-bottom: 100px;">
			<section>
				<legend>서명정보</legend>
				
				{% for info in sign_infos %}
				<div class="row-fluid">
					<span class="span2 offset4">{{ info.user }}</span>
					<span class="span3 btn btn-{% if info.is_signed == True %}success{% elif info.is_signed == False %}danger{% endif %}">
						{% if info.is_signed == True %}서명{% elif info.is_signed == False %}미서명{% endif %}
					</span>
				</div>
				{% endfor %}
				
			</section>
			<section>
				<legend>서명</legend>
				<div class="row-fluid">
					<form class="span8 offset2 form-horizontal label-left" novalidate="novalidate" method="POST" enctype="multipart/form-data" data-validate="parsley">{% csrf_token %}
						<input type="submit" value="{% if user_is_signed == True %}기존 서명을 지우고 새로 서명하기{% else %}서명하기{% endif %}" style="margin-top: 0px;" class="span12 btn btn-large btn-theme btn-rounded"/>
					</form>
				</div>
			</section>
			
		</div>

		<div id="sign_sections" class="span5">
			<section>
				<legend>서류 정보</legend>
				{% for key, value in data.items %}
				<div class="row-fluid section">
					<div class="span4 title">
						<span class="span12 btn btn-primary">{{ key }}</span>
					</div>
					<div class="span8 button">
						<span>{{ value }}</span>
					</div>
				</div>
				{% endfor %}
			</section>
		</div>
	</div>
</div>

{% endblock %}